---
version: 2

before:
  hooks:
    - sh -c "cd server/web && npm ci && npm run build"

builds:
  - id: build_cgo
    binary: hister
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=netgo,osusergo
    ignore:
      - goos: windows
        goarch: arm64
    overrides:
      - goos: windows
        goarch: amd64
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CGO_LDFLAGS=-lssp -static
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CGO_LDFLAGS=-static
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_LDFLAGS=-static
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang

archives:
  - formats: ["binary"]

dockers_v2:
  - images:
      - ghcr.io/asciimoo/hister

    tags:
      - "v{{.Version}}"
      - "{{ if not .IsNightly }}latest{{ end }}"
