package completion

import (
	"fmt"
	"io"
	"runtime"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// NushellHelp returns the long help text for the nushell completion subcommand.
func NushellHelp(name string) string {
	var configDir string
	switch runtime.GOOS {
	case "darwin":
		configDir = `"~/Library/Application Support/nushell"`
	case "windows":
		configDir = "%APPDATA%\\nushell"
	default:
		configDir = "~/.config/nushell"
	}
	return fmt.Sprintf(`Generate the autocompletion script for nushell.

To load completions:

  1. Generate the completions file:

    %[1]s completion nushell | save -f %[2]s/%[1]s-completions.nu

  2. Add the following line to your config.nu (open with: $nu.config-path | open):

    source %[1]s-completions.nu
`, name, configDir)
}

// GenNushell generates a nushell completion script for the given command.
// It leverages cobra's built-in __complete command for dynamic completions
// (via an external completer) and also generates static extern declarations
// for type-aware flag and argument completion in nushell.
func GenNushell(cmd *cobra.Command, w io.Writer) {
	name := cmd.Name()
	_, _ = fmt.Fprintf(w, "# Nushell completions for %s\n", name)
	_, _ = fmt.Fprintf(w, "# Generated by %s\n\n", name)

	// Emit a dynamic external completer that calls cobra's __complete command.
	// This handles ValidArgsFunction, dynamic flag completions, and subcommand
	// discovery automatically, anything cobra's completion engine supports.
	genDynamicCompleter(name, w)

	// Emit subcommand completers (so nushell suggests subcommands, not files)
	genSubcommandCompleters(cmd, w)

	// Collect and emit unique flag completion functions
	genAllCompletionFuncs(cmd, w)

	// Generate extern declarations for all commands
	genAllExterns(cmd, w)
}

// genDynamicCompleter emits a nushell external completer function that shells out to
// cobra's hidden __complete command for fully dynamic completions.
func genDynamicCompleter(name string, w io.Writer) {
	_, _ = fmt.Fprintf(w, `# Dynamic completer using cobra's __complete command
def "nu-complete %[1]s dynamic" [context: string] {
  let args = ($context | split row " " | skip 1)
  let completions = (^%[1]s __complete ...$args "" | lines)
  let directive_line = ($completions | last)
  let directive = ($directive_line | str replace ":" "" | into int)
  let results = ($completions | drop 1)
  $results | each { |line|
    let parts = ($line | split column "\t" value description)
    $parts | get 0
  }
}

`, name)
}

// isVisibleCommand reports whether a subcommand should appear in completions.
func isVisibleCommand(cmd *cobra.Command) bool {
	return cmd.IsAvailableCommand() && cmd.Name() != "help" && cmd.Name() != "completion"
}

// genSubcommandCompleters emits "def nu-complete ..." functions that return subcommand names
// for commands that have subcommands, so nushell suggests them instead of file paths.
func genSubcommandCompleters(cmd *cobra.Command, w io.Writer) {
	walkCommands(cmd, func(c *cobra.Command) {
		var children []*cobra.Command
		for _, child := range c.Commands() {
			if isVisibleCommand(child) {
				children = append(children, child)
			}
		}
		if len(children) == 0 {
			return
		}
		fullName := nushellCmdName(c)
		_, _ = fmt.Fprintf(w, "def \"nu-complete %s subcommands\" [] {\n  [\n", fullName)
		for _, child := range children {
			_, _ = fmt.Fprintf(w, "    { value: %q, description: %q },\n", child.Name(), child.Short)
		}
		_, _ = fmt.Fprintf(w, "  ]\n}\n\n")
	})
}

// genAllCompletionFuncs walks the tree and emits one "def nu-complete ..." per unique (owning-command, flag) pair.
func genAllCompletionFuncs(cmd *cobra.Command, w io.Writer) {
	emitted := map[string]bool{}
	walkCommands(cmd, func(c *cobra.Command) {
		// Only emit completers for flags directly owned by this command (local flags),
		// plus persistent flags on the root command.
		var flags *pflag.FlagSet
		if c.Parent() == nil {
			flags = c.PersistentFlags()
		} else {
			flags = c.LocalFlags()
		}
		flags.VisitAll(func(f *pflag.Flag) {
			if f.Hidden {
				return
			}
			values := flagCompletionValues(c, f)
			if len(values) == 0 {
				return
			}
			owner := nushellCmdName(c)
			key := owner + " " + f.Name
			if emitted[key] {
				return
			}
			emitted[key] = true
			quoted := make([]string, len(values))
			for i, v := range values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			_, _ = fmt.Fprintf(w, "def \"nu-complete %s %s\" [] {\n  [%s]\n}\n\n", owner, f.Name, strings.Join(quoted, " "))
		})
	})
}

// genAllExterns generates "export extern" for the root and all subcommands.
func genAllExterns(cmd *cobra.Command, w io.Writer) {
	walkCommands(cmd, func(c *cobra.Command) {
		genExtern(c, w)
	})
}

func hasVisibleSubcommands(cmd *cobra.Command) bool {
	return slices.ContainsFunc(cmd.Commands(), isVisibleCommand)
}

func genExtern(cmd *cobra.Command, w io.Writer) {
	fullName := nushellCmdName(cmd)
	_, _ = fmt.Fprintf(w, "# %s\n", nushellDescription(cmd))
	_, _ = fmt.Fprintf(w, "export extern \"%s\" [\n", fullName)

	if hasVisibleSubcommands(cmd) {
		_, _ = fmt.Fprintf(w, "  command?: string@\"nu-complete %s subcommands\"\n", fullName)
	} else {
		for _, arg := range nushellPositionalArgs(cmd) {
			_, _ = fmt.Fprintf(w, "  %s\n", arg)
		}
	}

	seen := map[string]bool{}
	writeFlags := func(flags *pflag.FlagSet, owner *cobra.Command) {
		flags.VisitAll(func(f *pflag.Flag) {
			if seen[f.Name] || f.Hidden {
				return
			}
			seen[f.Name] = true
			_, _ = fmt.Fprintf(w, "  %s\n", nushellFlagDecl(owner, f))
		})
	}

	// Inherited flags reference the root's completers
	if cmd.HasParent() {
		writeFlags(cmd.InheritedFlags(), cmd.Root())
	}
	// Local flags reference this command's completers
	writeFlags(cmd.LocalFlags(), cmd)

	if !seen["help"] {
		_, _ = fmt.Fprintf(w, "  --help(-h)  # Print help\n")
	}

	_, _ = fmt.Fprintf(w, "]\n\n")
}

// nushellFlagDecl generates a single nushell flag declaration.
func nushellFlagDecl(owner *cobra.Command, f *pflag.Flag) string {
	var b strings.Builder

	if f.Shorthand != "" {
		fmt.Fprintf(&b, "--%s(-%s)", f.Name, f.Shorthand)
	} else {
		fmt.Fprintf(&b, "--%s", f.Name)
	}

	typ := nushellType(f)
	if typ != "" {
		values := flagCompletionValues(owner, f)
		if len(values) > 0 {
			ownerName := nushellCmdName(owner)
			fmt.Fprintf(&b, ": %s@\"nu-complete %s %s\"", typ, ownerName, f.Name)
		} else {
			fmt.Fprintf(&b, ": %s", typ)
		}
	}

	if f.Usage != "" {
		fmt.Fprintf(&b, "  # %s", f.Usage)
	}

	return b.String()
}

// flagCompletionValues returns registered completion values for a flag.
// It calls the completion function with empty args/toComplete to extract static values.
// The shell directive is intentionally discarded, nushell externs don't support
// runtime directives, so we only use this for statically registered choices.
func flagCompletionValues(cmd *cobra.Command, f *pflag.Flag) []string {
	fn, ok := cmd.GetFlagCompletionFunc(f.Name)
	if !ok {
		return nil
	}
	values, _ := fn(cmd, []string{}, "")
	if len(values) == 0 {
		return nil
	}
	cleaned := make([]string, len(values))
	for i, v := range values {
		if before, _, found := strings.Cut(v, "\t"); found {
			cleaned[i] = before
		} else {
			cleaned[i] = v
		}
	}
	return cleaned
}

// nushellCmdName returns the full space-separated command name.
func nushellCmdName(cmd *cobra.Command) string {
	var parts []string
	for c := cmd; c != nil; c = c.Parent() {
		parts = append(parts, c.Name())
	}
	slices.Reverse(parts)
	return strings.Join(parts, " ")
}

func nushellDescription(cmd *cobra.Command) string {
	if cmd.Short != "" {
		return cmd.Short
	}
	return cmd.Name()
}

type argGroup struct {
	text     string
	optional bool
}

// nushellPositionalArgs parses the Use string to extract positional arguments.
// It handles patterns like: "URL [URL...]", "[search terms]", "BROWSER_TYPE DB_PATH", "[FILENAME]"
func nushellPositionalArgs(cmd *cobra.Command) []string {
	use := cmd.Use
	_, argStr, found := strings.Cut(use, " ")
	if !found {
		return nil
	}

	// Parse bracket groups and bare tokens
	var groups []argGroup
	for len(argStr) > 0 {
		argStr = strings.TrimLeft(argStr, " ")
		if argStr == "" {
			break
		}
		if argStr[0] == '[' {
			end := strings.Index(argStr, "]")
			if end < 0 {
				end = len(argStr)
			}
			groups = append(groups, argGroup{argStr[1:end], true})
			argStr = argStr[min(end+1, len(argStr)):]
		} else {
			token, rest, _ := strings.Cut(argStr, " ")
			groups = append(groups, argGroup{token, false})
			argStr = rest
		}
	}

	var args []string
	seenNames := map[string]bool{}

	for _, g := range groups {
		text := g.text
		isRest := strings.HasSuffix(text, "...")
		text = strings.TrimSuffix(text, "...")
		text = strings.TrimSpace(text)

		// Use the last word as the arg name (handles "search terms" -> "terms")
		words := strings.Fields(text)
		if len(words) == 0 {
			continue
		}

		// Bracket groups with multiple words (e.g. "[search terms]") are treated as
		// variadic rest args, since nushell can't express multi-word positional groups.
		if len(words) > 1 && !isRest {
			isRest = true
		}

		name := strings.ToLower(strings.ReplaceAll(words[len(words)-1], "-", "_"))

		// If this name was already seen as a required arg and now appears as rest/optional,
		// upgrade the previous entry to rest args instead of adding a duplicate.
		if seenNames[name] {
			if isRest || g.optional {
				for i, a := range args {
					if strings.Contains(a, name+": string") {
						args[i] = fmt.Sprintf("...%s: string", name)
						break
					}
				}
			}
			continue
		}
		seenNames[name] = true

		switch {
		case isRest:
			args = append(args, fmt.Sprintf("...%s: string", name))
		case g.optional:
			args = append(args, fmt.Sprintf("%s?: string", name))
		default:
			args = append(args, fmt.Sprintf("%s: string", name))
		}
	}
	return args
}

// nushellType maps pflag types to nushell types.
func nushellType(f *pflag.Flag) string {
	switch f.Value.Type() {
	case "bool":
		return ""
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return "int"
	case "float32", "float64":
		return "float"
	default:
		return "string"
	}
}

// walkCommands visits cmd and all its visible subcommands (excluding "help" and "completion").
func walkCommands(cmd *cobra.Command, fn func(*cobra.Command)) {
	fn(cmd)
	for _, child := range cmd.Commands() {
		if !isVisibleCommand(child) {
			continue
		}
		walkCommands(child, fn)
	}
}
