export type ThemeId = 'forest' | 'ocean' | 'desert' | 'berry' | 'mono';

interface ThemeDef {
  id: ThemeId;
  name: string;
  swatches: [string, string, string];
  light: Record<string, string>;
  dark: Record<string, string>;
}

const THEME_DEFS: ThemeDef[] = [
  {
    id: 'forest',
    name: 'Forest',
    swatches: ['#2D5A3D', '#3A7A78', '#C27A55'],
    // Default — no overrides needed, CSS values used as-is
    light: {},
    dark: {},
  },
  {
    id: 'ocean',
    name: 'Ocean',
    swatches: ['#1E3A5F', '#4A90D9', '#87CEEB'],
    light: {
      // Backgrounds — cool blue-grey
      '--background': '#E8EEF4',
      '--foreground': '#1A2A3A',
      '--card': '#F0F4F8',
      '--card-foreground': '#1A2A3A',
      '--popover': '#F0F4F8',
      '--popover-foreground': '#1A2A3A',
      '--primary': '#1A2A3A',
      '--primary-foreground': '#F0F4F8',
      '--secondary': '#D0DAE4',
      '--secondary-foreground': '#1A2A3A',
      '--muted': '#D0DAE4',
      '--muted-foreground': '#5A7088',
      '--accent': '#B8C8D8',
      '--accent-foreground': '#1A2A3A',
      '--destructive': '#C05A6A',
      '--border': '#B8C8D8',
      '--input': '#D0DAE4',
      '--ring': '#1E3A5F',
      '--sidebar': '#DDE6EE',
      '--sidebar-foreground': '#1A2A3A',
      '--sidebar-primary': '#1E3A5F',
      '--sidebar-primary-foreground': '#F0F4F8',
      '--sidebar-accent': '#D0DAE4',
      '--sidebar-accent-foreground': '#1A2A3A',
      '--sidebar-border': '#B8C8D8',
      '--sidebar-ring': '#1E3A5F',
      // Accents
      '--hister-coral': '#5A8AB8',
      '--hister-indigo': '#1E3A5F',
      '--hister-teal': '#4A90D9',
      '--hister-amber': '#6AA0C8',
      '--hister-rose': '#8A6A98',
      // Brutal
      '--brutal-bg': '#E0E8F0',
      '--brutal-border': '#1A2A3A',
      '--brutal-card': '#F0F4F8',
      '--brutal-shadow': '#1A2A3A',
      // Semantic
      '--text-primary': '#1A2A3A',
      '--text-secondary': '#5A7088',
      '--page-bg': '#E8EEF4',
      '--card-surface': '#F0F4F8',
      '--text-primary-brand': '#1A2A3A',
      '--text-secondary-brand': '#5A7088',
      '--text-muted-brand': '#5A7088',
      '--muted-surface': '#D0DAE4',
      '--border-brand': '#B8C8D8',
      '--border-muted-brand': '#B8C8D8',
      // Charts
      '--chart-1': '#5A8AB8',
      '--chart-2': '#1E3A5F',
      '--chart-3': '#6AA0C8',
      '--chart-4': '#8A6A98',
      '--chart-5': '#4A90D9',
    },
    dark: {
      '--background': '#0E1A28',
      '--foreground': '#D0DEE8',
      '--card': '#162838',
      '--card-foreground': '#D0DEE8',
      '--popover': '#162838',
      '--popover-foreground': '#D0DEE8',
      '--primary': '#D0DEE8',
      '--primary-foreground': '#0E1A28',
      '--secondary': '#1E3248',
      '--secondary-foreground': '#D0DEE8',
      '--muted': '#1E3248',
      '--muted-foreground': '#7A98B0',
      '--accent': '#283E58',
      '--accent-foreground': '#D0DEE8',
      '--destructive': '#D0808E',
      '--border': '#283E58',
      '--input': '#283E58',
      '--ring': '#5A9AD0',
      '--sidebar': '#121E2E',
      '--sidebar-foreground': '#D0DEE8',
      '--sidebar-primary': '#5A9AD0',
      '--sidebar-primary-foreground': '#D0DEE8',
      '--sidebar-accent': '#283E58',
      '--sidebar-accent-foreground': '#D0DEE8',
      '--sidebar-border': '#283E58',
      '--sidebar-ring': '#5A9AD0',
      '--hister-coral': '#78AAD0',
      '--hister-indigo': '#5A9AD0',
      '--hister-teal': '#68B8D8',
      '--hister-amber': '#80C0E0',
      '--hister-rose': '#A090C0',
      '--brutal-bg': '#0E1A28',
      '--brutal-border': '#385068',
      '--brutal-card': '#162838',
      '--brutal-shadow': '#080E18',
      '--text-primary': '#D0DEE8',
      '--text-secondary': '#7A98B0',
      '--page-bg': '#0E1A28',
      '--card-surface': '#162838',
      '--text-primary-brand': '#D0DEE8',
      '--text-secondary-brand': '#7A98B0',
      '--text-muted-brand': '#4A6880',
      '--muted-surface': '#1E3248',
      '--border-brand': '#283E58',
      '--border-muted-brand': '#283E58',
      '--chart-1': '#78AAD0',
      '--chart-2': '#5A9AD0',
      '--chart-3': '#80C0E0',
      '--chart-4': '#A090C0',
      '--chart-5': '#68B8D8',
    },
  },
  {
    id: 'desert',
    name: 'Desert',
    swatches: ['#8B5A3A', '#C27A55', '#D4A860'],
    light: {
      '--background': '#F4EADE',
      '--foreground': '#3A2818',
      '--card': '#FAF4EA',
      '--card-foreground': '#3A2818',
      '--popover': '#FAF4EA',
      '--popover-foreground': '#3A2818',
      '--primary': '#3A2818',
      '--primary-foreground': '#FAF4EA',
      '--secondary': '#E8D8C4',
      '--secondary-foreground': '#3A2818',
      '--muted': '#E8D8C4',
      '--muted-foreground': '#7A6248',
      '--accent': '#D8C4A8',
      '--accent-foreground': '#3A2818',
      '--destructive': '#C05A4A',
      '--border': '#D8C4A8',
      '--input': '#E8D8C4',
      '--ring': '#8B5A3A',
      '--sidebar': '#EEE2D4',
      '--sidebar-foreground': '#3A2818',
      '--sidebar-primary': '#8B5A3A',
      '--sidebar-primary-foreground': '#FAF4EA',
      '--sidebar-accent': '#E8D8C4',
      '--sidebar-accent-foreground': '#3A2818',
      '--sidebar-border': '#D8C4A8',
      '--sidebar-ring': '#8B5A3A',
      '--hister-coral': '#C27A55',
      '--hister-indigo': '#8B5A3A',
      '--hister-teal': '#A08858',
      '--hister-amber': '#D4A860',
      '--hister-rose': '#B87858',
      '--brutal-bg': '#F0E4D4',
      '--brutal-border': '#3A2818',
      '--brutal-card': '#FAF4EA',
      '--brutal-shadow': '#3A2818',
      '--text-primary': '#3A2818',
      '--text-secondary': '#7A6248',
      '--page-bg': '#F4EADE',
      '--card-surface': '#FAF4EA',
      '--text-primary-brand': '#3A2818',
      '--text-secondary-brand': '#7A6248',
      '--text-muted-brand': '#7A6248',
      '--muted-surface': '#E8D8C4',
      '--border-brand': '#D8C4A8',
      '--border-muted-brand': '#D8C4A8',
      '--chart-1': '#C27A55',
      '--chart-2': '#8B5A3A',
      '--chart-3': '#D4A860',
      '--chart-4': '#B87858',
      '--chart-5': '#A08858',
    },
    dark: {
      '--background': '#1E1610',
      '--foreground': '#E8D8C8',
      '--card': '#2A2018',
      '--card-foreground': '#E8D8C8',
      '--popover': '#2A2018',
      '--popover-foreground': '#E8D8C8',
      '--primary': '#E8D8C8',
      '--primary-foreground': '#1E1610',
      '--secondary': '#382A1E',
      '--secondary-foreground': '#E8D8C8',
      '--muted': '#382A1E',
      '--muted-foreground': '#A08868',
      '--accent': '#443428',
      '--accent-foreground': '#E8D8C8',
      '--destructive': '#D08070',
      '--border': '#443428',
      '--input': '#443428',
      '--ring': '#C0885A',
      '--sidebar': '#241A12',
      '--sidebar-foreground': '#E8D8C8',
      '--sidebar-primary': '#C0885A',
      '--sidebar-primary-foreground': '#E8D8C8',
      '--sidebar-accent': '#443428',
      '--sidebar-accent-foreground': '#E8D8C8',
      '--sidebar-border': '#443428',
      '--sidebar-ring': '#C0885A',
      '--hister-coral': '#D4986A',
      '--hister-indigo': '#C0885A',
      '--hister-teal': '#C0A870',
      '--hister-amber': '#E0C070',
      '--hister-rose': '#D09878',
      '--brutal-bg': '#1E1610',
      '--brutal-border': '#584838',
      '--brutal-card': '#2A2018',
      '--brutal-shadow': '#100A06',
      '--text-primary': '#E8D8C8',
      '--text-secondary': '#A08868',
      '--page-bg': '#1E1610',
      '--card-surface': '#2A2018',
      '--text-primary-brand': '#E8D8C8',
      '--text-secondary-brand': '#A08868',
      '--text-muted-brand': '#786048',
      '--muted-surface': '#382A1E',
      '--border-brand': '#443428',
      '--border-muted-brand': '#443428',
      '--chart-1': '#D4986A',
      '--chart-2': '#C0885A',
      '--chart-3': '#E0C070',
      '--chart-4': '#D09878',
      '--chart-5': '#C0A870',
    },
  },
  {
    id: 'berry',
    name: 'Berry',
    swatches: ['#6A3A7A', '#9858A8', '#D070A0'],
    light: {
      '--background': '#F0E8F0',
      '--foreground': '#2A1830',
      '--card': '#F8F2F8',
      '--card-foreground': '#2A1830',
      '--popover': '#F8F2F8',
      '--popover-foreground': '#2A1830',
      '--primary': '#2A1830',
      '--primary-foreground': '#F8F2F8',
      '--secondary': '#E0D0E0',
      '--secondary-foreground': '#2A1830',
      '--muted': '#E0D0E0',
      '--muted-foreground': '#6A5070',
      '--accent': '#D0BCD0',
      '--accent-foreground': '#2A1830',
      '--destructive': '#C05070',
      '--border': '#D0BCD0',
      '--input': '#E0D0E0',
      '--ring': '#6A3A7A',
      '--sidebar': '#E8DCE8',
      '--sidebar-foreground': '#2A1830',
      '--sidebar-primary': '#6A3A7A',
      '--sidebar-primary-foreground': '#F8F2F8',
      '--sidebar-accent': '#E0D0E0',
      '--sidebar-accent-foreground': '#2A1830',
      '--sidebar-border': '#D0BCD0',
      '--sidebar-ring': '#6A3A7A',
      '--hister-coral': '#9858A8',
      '--hister-indigo': '#6A3A7A',
      '--hister-teal': '#7A58A0',
      '--hister-amber': '#A878B0',
      '--hister-rose': '#D070A0',
      '--brutal-bg': '#EAE0EA',
      '--brutal-border': '#2A1830',
      '--brutal-card': '#F8F2F8',
      '--brutal-shadow': '#2A1830',
      '--text-primary': '#2A1830',
      '--text-secondary': '#6A5070',
      '--page-bg': '#F0E8F0',
      '--card-surface': '#F8F2F8',
      '--text-primary-brand': '#2A1830',
      '--text-secondary-brand': '#6A5070',
      '--text-muted-brand': '#6A5070',
      '--muted-surface': '#E0D0E0',
      '--border-brand': '#D0BCD0',
      '--border-muted-brand': '#D0BCD0',
      '--chart-1': '#9858A8',
      '--chart-2': '#6A3A7A',
      '--chart-3': '#A878B0',
      '--chart-4': '#D070A0',
      '--chart-5': '#7A58A0',
    },
    dark: {
      '--background': '#180E1E',
      '--foreground': '#E0D0E8',
      '--card': '#221828',
      '--card-foreground': '#E0D0E8',
      '--popover': '#221828',
      '--popover-foreground': '#E0D0E8',
      '--primary': '#E0D0E8',
      '--primary-foreground': '#180E1E',
      '--secondary': '#2E2038',
      '--secondary-foreground': '#E0D0E8',
      '--muted': '#2E2038',
      '--muted-foreground': '#9880A0',
      '--accent': '#3A2848',
      '--accent-foreground': '#E0D0E8',
      '--destructive': '#D880A0',
      '--border': '#3A2848',
      '--input': '#3A2848',
      '--ring': '#9A78B8',
      '--sidebar': '#1E1424',
      '--sidebar-foreground': '#E0D0E8',
      '--sidebar-primary': '#9A78B8',
      '--sidebar-primary-foreground': '#E0D0E8',
      '--sidebar-accent': '#3A2848',
      '--sidebar-accent-foreground': '#E0D0E8',
      '--sidebar-border': '#3A2848',
      '--sidebar-ring': '#9A78B8',
      '--hister-coral': '#B880C8',
      '--hister-indigo': '#9A78B8',
      '--hister-teal': '#A088C0',
      '--hister-amber': '#C098D0',
      '--hister-rose': '#E090B0',
      '--brutal-bg': '#180E1E',
      '--brutal-border': '#4A3858',
      '--brutal-card': '#221828',
      '--brutal-shadow': '#0C060E',
      '--text-primary': '#E0D0E8',
      '--text-secondary': '#9880A0',
      '--page-bg': '#180E1E',
      '--card-surface': '#221828',
      '--text-primary-brand': '#E0D0E8',
      '--text-secondary-brand': '#9880A0',
      '--text-muted-brand': '#685078',
      '--muted-surface': '#2E2038',
      '--border-brand': '#3A2848',
      '--border-muted-brand': '#3A2848',
      '--chart-1': '#B880C8',
      '--chart-2': '#9A78B8',
      '--chart-3': '#C098D0',
      '--chart-4': '#E090B0',
      '--chart-5': '#A088C0',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    swatches: ['#4A4440', '#7A7268', '#A09888'],
    light: {
      '--background': '#ECECEC',
      '--foreground': '#2A2A2A',
      '--card': '#F5F5F5',
      '--card-foreground': '#2A2A2A',
      '--popover': '#F5F5F5',
      '--popover-foreground': '#2A2A2A',
      '--primary': '#2A2A2A',
      '--primary-foreground': '#F5F5F5',
      '--secondary': '#DCDCDC',
      '--secondary-foreground': '#2A2A2A',
      '--muted': '#DCDCDC',
      '--muted-foreground': '#6A6A6A',
      '--accent': '#CCCCCC',
      '--accent-foreground': '#2A2A2A',
      '--destructive': '#8A6060',
      '--border': '#CCCCCC',
      '--input': '#DCDCDC',
      '--ring': '#4A4440',
      '--sidebar': '#E4E4E4',
      '--sidebar-foreground': '#2A2A2A',
      '--sidebar-primary': '#4A4440',
      '--sidebar-primary-foreground': '#F5F5F5',
      '--sidebar-accent': '#DCDCDC',
      '--sidebar-accent-foreground': '#2A2A2A',
      '--sidebar-border': '#CCCCCC',
      '--sidebar-ring': '#4A4440',
      '--hister-coral': '#7A7268',
      '--hister-indigo': '#4A4440',
      '--hister-teal': '#5A5856',
      '--hister-amber': '#8A8278',
      '--hister-rose': '#6A5A58',
      '--brutal-bg': '#E8E8E8',
      '--brutal-border': '#2A2A2A',
      '--brutal-card': '#F5F5F5',
      '--brutal-shadow': '#2A2A2A',
      '--text-primary': '#2A2A2A',
      '--text-secondary': '#6A6A6A',
      '--page-bg': '#ECECEC',
      '--card-surface': '#F5F5F5',
      '--text-primary-brand': '#2A2A2A',
      '--text-secondary-brand': '#6A6A6A',
      '--text-muted-brand': '#6A6A6A',
      '--muted-surface': '#DCDCDC',
      '--border-brand': '#CCCCCC',
      '--border-muted-brand': '#CCCCCC',
      '--chart-1': '#7A7268',
      '--chart-2': '#4A4440',
      '--chart-3': '#8A8278',
      '--chart-4': '#6A5A58',
      '--chart-5': '#5A5856',
    },
    dark: {
      '--background': '#181818',
      '--foreground': '#E0E0E0',
      '--card': '#222222',
      '--card-foreground': '#E0E0E0',
      '--popover': '#222222',
      '--popover-foreground': '#E0E0E0',
      '--primary': '#E0E0E0',
      '--primary-foreground': '#181818',
      '--secondary': '#2C2C2C',
      '--secondary-foreground': '#E0E0E0',
      '--muted': '#2C2C2C',
      '--muted-foreground': '#909090',
      '--accent': '#363636',
      '--accent-foreground': '#E0E0E0',
      '--destructive': '#B09090',
      '--border': '#363636',
      '--input': '#363636',
      '--ring': '#8A8278',
      '--sidebar': '#1E1E1E',
      '--sidebar-foreground': '#E0E0E0',
      '--sidebar-primary': '#8A8278',
      '--sidebar-primary-foreground': '#E0E0E0',
      '--sidebar-accent': '#363636',
      '--sidebar-accent-foreground': '#E0E0E0',
      '--sidebar-border': '#363636',
      '--sidebar-ring': '#8A8278',
      '--hister-coral': '#A09888',
      '--hister-indigo': '#8A8278',
      '--hister-teal': '#90887A',
      '--hister-amber': '#B0A898',
      '--hister-rose': '#988888',
      '--brutal-bg': '#181818',
      '--brutal-border': '#484848',
      '--brutal-card': '#222222',
      '--brutal-shadow': '#0A0A0A',
      '--text-primary': '#E0E0E0',
      '--text-secondary': '#909090',
      '--page-bg': '#181818',
      '--card-surface': '#222222',
      '--text-primary-brand': '#E0E0E0',
      '--text-secondary-brand': '#909090',
      '--text-muted-brand': '#606060',
      '--muted-surface': '#2C2C2C',
      '--border-brand': '#363636',
      '--border-muted-brand': '#363636',
      '--chart-1': '#A09888',
      '--chart-2': '#8A8278',
      '--chart-3': '#B0A898',
      '--chart-4': '#988888',
      '--chart-5': '#90887A',
    },
  },
];

export const THEMES = THEME_DEFS;

const STORAGE_KEY = 'hister-theme';

// Collect all variable names that any non-forest theme can set,
// so we know what to clean up when switching back to forest.
const ALL_OVERRIDE_KEYS = [
  ...new Set(THEME_DEFS.flatMap((t) => [...Object.keys(t.light), ...Object.keys(t.dark)])),
];

export function loadTheme(): ThemeId {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored && THEME_DEFS.some((t) => t.id === stored)) {
      return stored as ThemeId;
    }
  } catch {
    // SSR or storage unavailable
  }
  return 'forest';
}

export function saveTheme(id: ThemeId): void {
  try {
    localStorage.setItem(STORAGE_KEY, id);
  } catch {
    // storage unavailable
  }
}

export function applyTheme(id: ThemeId, currentMode: string | undefined): void {
  const theme = THEME_DEFS.find((t) => t.id === id);
  if (!theme) return;

  const mode = currentMode === 'dark' ? 'dark' : 'light';
  const colors = theme[mode];
  const el = document.documentElement;

  if (id === 'forest') {
    // Remove all overrides so CSS defaults take over
    for (const key of ALL_OVERRIDE_KEYS) {
      el.style.removeProperty(key);
    }
  } else {
    // First clear any stale keys from a previous theme
    for (const key of ALL_OVERRIDE_KEYS) {
      if (!(key in colors)) {
        el.style.removeProperty(key);
      }
    }
    for (const [key, value] of Object.entries(colors)) {
      el.style.setProperty(key, value);
    }
  }
}
